In [1]:
import numpy as np
import pandas as pd

In [2]:
import requests

In [5]:
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [8]:
data = resp.json()
data[0]['title']

'QST: read_excel - "odf engine" remove "\\n" when reading multi-line cell from “ods” file'

In [10]:
issues = pd.DataFrame(data, columns=['number', 'title', 'label', 'state'])

In [11]:
issues

number                                              title  label state
0    41625  QST: read_excel - "odf engine" remove "\n" whe...    NaN  open
1    41624               REF: simplify maybe_cast_to_datetime    NaN  open
2    41623       QST: Error in Pandas to_datetime conversion?    NaN  open
3    41622           REF: convert_dtypes return dtype objects    NaN  open
4    41621                           TYP: NaTType comparisons    NaN  open
5    41620             TYP: __future__ annotations in parsers    NaN  open
6    41619  REF: rename kw `escape`  `escape_html` in `Sty...    NaN  open
7    41618                                     REF: _try_cast    NaN  open
8    41617  BUG: Date offset on numpy datetime64 does not ...    NaN  open
9    41616  BUG: very very slow when append  long dictiona...    NaN  open
10   41615            CLN: various related to numeric indexes    NaN  open
11   41614  DOC: use shared docstrings for repeated args i...    NaN  open
12   41613  DOC: add to_latex to io.rst and other cross-re...    NaN  open
13   41612                       REGR: CategoricalIndex(None)    NaN  open
14   41611  REF: re-use sanitize_array in DataFrame._sanit...    NaN  open
15   41610  TYP/DOC: Use Protocols for file-like objects i...    NaN  open
16   41607                                    TST: Old issues    NaN  open
17   41606  BUG: case argument ignored when regex is False...    NaN  open
18   41604  QST: | (or) behavior when working with two ser...    NaN  open
19   41602  BUG: case argument ignored when regex is False...    NaN  open
20   41598  PERF: Calling slowpath for every group in tran...    NaN  open
21   41596       BUG: groupby performance regression in 1.2.x    NaN  open
22   41595            WIP: Fail on Python 3.10 Pytest Failure    NaN  open
23   41594               TYP and DOC: pd.merge accepts Series    NaN  open
24   41590  [ArrowStringArray] PERF: use pyarrow.compute.r...    NaN  open
25   41589  ENH: Deprecate non-keyword arguments for Multi...    NaN  open
26   41588  TYP: IntervalIndex.right/left might be infered...    NaN  open
27   41586                               DEPR: Timestamp.freq    NaN  open
28   41585  BUG: concatenation on monthstart indexes in wr...    NaN  open
29   41584  BUG: GroupBy.transform() unexpectedly coerces ...    NaN  open

In [12]:
#request란 파이썬에서 HTTP와 관련된 작업, 웹페이지에 원하는 작업 요청을 할 수 있는 라이브러리
#웨페이지에서 원하는 정보를 얻기 위해 해당 데이터의 주소 html코드를 불러오는 역할
#get()란 ()안에 들어갈 웨페이지의 html 구성요소들을 얻어주는 함수

In [15]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1': range(7)})

In [16]:
df2 = pd.DataFrame({'key': ['a','b','d'], 'data2': range(3)})

In [17]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [18]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [19]:
pd.merge(df1, df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [20]:
#중복된 컬럼 이름을 키로 시용함

In [21]:
pd.merge(df1, df2, on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [23]:
df3 = pd.DataFrame({'lkey': ['b','b','a','c','a','a','b'], 'data1': range(7)})

In [24]:
df4 = pd.DataFrame({'rkey': ['a','b','d'], 'data2':range(3)})

In [25]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

In [26]:
pd.merge(df1, df2, how='outer')

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [27]:
#'outer'는 합집합

In [32]:
arr = np.arange(12).reshape((3,4))

In [33]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [36]:
s1 = pd.Series([0, 1], index = ['a', 'b'])
s2 = pd.Series([2,3,4], index = ['c', 'd', 'e'])
s3 = pd.Series([5,6], index = ['f', 'g'])

In [37]:
pd.concat([s1,s2,s3],axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [38]:
#axis=0이면 Series객체, axis=1이면 DataFrmae 객체

In [39]:
s4 = pd.concat([s1, s3])

In [40]:
s4

a    0
b    1
f    5
g    6
dtype: int64

In [41]:
pd.concat([s1,s4], axis=1)

0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [42]:
pd.concat([s1,s4], axis=1, join='inner')

0  1
a  0  0
b  1  1

In [43]:
pd.concat([s1,s4], axis=1).reindex(['a','c','b','e'])

0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  1.0
e  NaN  NaN

In [44]:
result=pd.concat([s1,s1,s3], keys=['one','two','three'])

In [45]:
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [46]:
result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

In [48]:
pd.concat([s1,s2,s3], axis=1, keys=['one', 'two', 'three'])

one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [50]:
a=pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],
           index = ['f','e','d','c','b','a'])
b=pd.Series(np.arange(len(a), dtype=np.float64), index=['f','e','d','c','b','a'])

In [51]:
b[-1] = np.nan

In [52]:
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [53]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [54]:
np.where(pd.isnull(a),b,a)

array([0. , 2.5, 2. , 3.5, 4.5, nan])

In [55]:
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [58]:
df1 = pd.DataFrame({'a': [1., np.nan, 5., np.nan],
                   'b': [np.nan, 2., np.nan, 6.],
                   'c': range(2, 18, 4)})

In [59]:
df2 = pd.DataFrame({'a': [5., 4., np.nan, 3., 7.], 'b': [np.nan, 3., 4., 6., 8.]})

In [60]:
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [61]:
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [63]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN